### ISSUE TITLE
sks-keyservers.net no longer available

### ISSUE THREAD

**Issue by ADumaine** [HorizenOfficial/zen-node-docker#21]
Should be removed from Dockerfile. 
![image](https://user-images.githubusercontent.com/1069218/137226682-d5955b2d-5b47-4b41-bb42-2ea431dad557.png)

**Comment by cronicc** [comment]
Fixed with https://github.com/HorizenOfficial/zen-node-docker/commit/bf8082d916cbc2aa213abd91275ca63d86ea950f
