### ISSUE TITLE
Image cannot be pulled from hub.docker.com

### ISSUE THREAD

**Issue by L0wPressu7e** [HorizenOfficial/zen-node-docker#22]
https://hub.docker.com/r/zencash/zen-node
`docker pull zencash/zen-node` - command does not work, returns 

> ╰─ docker pull zencash/zen-node
> Using default tag: latest
> Error response from daemon: manifest for zencash/zen-node:latest not found: manifest unknown: manifest unknown

I'll build it from github, just wanted to let you know.

**Comment by cronicc** [comment]
Hi @L0wPressu7e,

version 3.0.0 was unpublished from hub.docker.com while we investigated this issue https://github.com/HorizenOfficial/zen/issues/402.

v3.0.1 has been published that addresses it, `latest` and `v3.0.1` tags are now available on hub.docker.com again. As you've built the container locally please make sure to update to v3.0.1.
