### ISSUE TITLE
Upgrading Zen node from v2.0.24 to v3.0.2 /3 asking to reindex

### ISSUE THREAD

**Issue by debasish22** [HorizenOfficial/zen-node-docker#23]
Hello ,

I have a zen node running which was working fine with version v2.0.24 but suddenly stooped syncing, when checked the logs it said the node version is deprecated at a specific block and needed to be upgraded . So the latest version being v3.0.3 tried to upgrade but the node does not sync and getting message to use -reindex to recover.

Can any one suggest 
1.if -reindex is really needed and is it safe for the existing data if we apply reindex .
2.How many days it takes to re-index a historical node
<img width="769" alt="Reindex-HorizenNode" src="https://user-images.githubusercontent.com/30689502/144982409-156b96ac-a4cb-467c-b7d1-c61185e0ca02.PNG">
.

**Comment by cronicc** [comment]
@debasish22 -reindex is a safe operation, but can take 3+ days. Instead I suggest using `-reindexfast` which should take about half a day.
