### ISSUE TITLE
how to reindex?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [HorizenOfficial/zen-node-docker#37]
the container just exits and this is the message:

```
Error: Error: Disk space is low!
Error: Error: Disk space is low!
Starting with UID/GID : 9001/9001

Allowing RPC access from: 0.0.0.0/0 ::/0

Zcash - fetch-params.sh

Zen uses the same zkSNARK parameters generated by ZCash.
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
: Error opening block database.
Please restart with -reindex to recover.
```

how can I restart the container with a new config without losing the chain?
also, my hard drive has 80gb, is this enough space?

```
df -h

Filesystem      Size  Used Avail Use% Mounted on
tmpfs           383M  840K  382M   1% /run
/dev/sda1        75G   72G   32M 100% /
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      253M  142K  252M   1% /boot/efi
tmpfs           383M     0  383M   0% /run/user/0
```

**Comment by ldehaan9** [comment]
Hi there. The Zcash parameters directory uses about 1.6GB. You've got about 32MB free, so you're REALLY hurting for space. Can you safely reduce the size of your swap file?

The .zen directory on one of my nodes is about 75GB so I believe you'll have to expand the container. Don't know anything about containers so can't help there.

I've wondered whether you can have a single shared disk with just the zcash parameters, mount it read-only, and create a link to it in the directory structure of each node/container. This way, all the containers/virtual machines can use the one disk. Hope this helps.

**Comment by ldehaan9** [comment]
Just thought of this. Reindexing will likely take way too long. You're better off getting a relatively recent copy of the database from https://bootstraps.ultimatenodes.io/horizen/masternode/.

**Comment by minzak** [comment]
> Just thought of this. Reindexing will likely take way too long. You're better off getting a relatively recent copy of the database from https://bootstraps.ultimatenodes.io/horizen/masternode/.

Links does not work. (

**Comment by ldehaan9** [comment]
Hi Olexandr,
Sorry about that. That server is no longer online.
Thanks to Psyrax, this one is now available. Note the database is 65GB. Have a good evening.
ttps://bootstraps.zen-solutions.io/

 Laurens 

    On Wednesday, June 21, 2023 at 01:07:03 PM PDT, Olexandr Minzak ***@***.***> wrote:  
 
 



Just thought of this. Reindexing will likely take way too long. You're better off getting a relatively recent copy of the database from https://bootstraps.ultimatenodes.io/horizen/masternode/.


Links does not work. (

**Comment by cronicc** [comment]
Thanks @psyraxaus for providing the seeds!

@hp8wvvvgnj6asjm7 75GB is not enough I'm afraid when considering the OS. To answer the question on how to reindex, start the container with `-e OPTS="-reindexfast"` and wait for the reindex to complete, then stop the container and remove -reindexfast from OPTS before the next container (re)start.

Closing the issue, feel free to reopen should you need additional help.
