### ISSUE TITLE
is there a way to attach a volume?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [HorizenOfficial/zen-node-docker#38]
I would like to store the zen chain in a persistent volume in case I have to reconfigure the container.
Is there a practical way to switch wallet.dat files and restart the container?

**Comment by cronicc** [comment]
You can use a named volumes like this:
```
docker volume create zen-data
docker volume create zcash-params
docker run --rm -v "zen-data:/mnt/zen:rw" -v "zcash-params:/mnt/zcash-params:rw" zencash/zen-node:latest
```

Or bind mounts (paths on the host) like this:
```
mkdir -p /path/to/zen-data
mkdir -p /path/to/zcash-params
docker run --rm -v "/path/to/zen-data:/mnt/zen:rw" -v "/path/to/zcash-params:/mnt/zcash-params:rw" zencash/zen-node:latest
```

The container creates volumes to persist data by default. If you want to migrate existing block data and wallet.dat, take a look at the folders in `/var/lib/docker/volumes`.
